# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

services:
 - mysql
 - postgresql

addons:
apt:
  packages:
    - unixodbc
    - unixodbc-dev
    - libmyodbc
    - libsqliteodbc
    - odbc-postgresql

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

julia:
  - 1.0
  - 1.3
  - nightly

env:
  - JULIA_PROJECT="@."
  - ODBC_TEST_DRIVERS="mysql, postgresql"

matrix:
  exclude:
    - os: osx
      arch: x86
    - os: linux
      arch: x86
  allow_failures:
  - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("ODBC")'
        - julia --project=docs/ docs/make.jl
      after_success: skip

before_install:
- |-
    case $TRAVIS_OS_NAME in windows)
        choco install mysql
        dir C:\\tools\\mysql
        dir C:\\tools\\mysql\\current
        dir C:\\tools\\mysql\\current\\bin
        C:\\tools\\mysql\\current\\bin\\mysqld --install
        ;;
    esac
- cp ./test/setup/.odbcinst.ini $HOME
- odbcinst -i -s -h -f ./test/setup/mysqltest.odbc.ini
- odbcinst -i -s -h -f ./test/setup/postgresqltest.odbc.ini
- odbcinst -i -s -h -f ./test/setup/mssqltest.odbc.ini
- echo -e "\n[odbc]\nlocal-infile=1\n" >> $HOME/.my.cnf

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install mysql; brew services start mysql; fi

notifications:
  email: false

after_success:
   - julia -e 'ENV["TRAVIS_JULIA_VERSION"] == "1.3" && ENV["TRAVIS_OS_NAME"] != "linux" && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
